// 小学英语单词数据库 - 1200个常用单词
// 按年级分类，每年级200个单词

const wordDatabase = {
  1: [
    // 1年级 - 最基础日常词汇 (200个)
    
    // 动物类 (30个)
    { word: "cat", chinese: "猫", pronunciation: "/kæt/", example: "I have a cat. 我有一只猫。", tip: "像'咖啡'的发音" },
    { word: "dog", chinese: "狗", pronunciation: "/dɔːɡ/", example: "The dog is big. 这只狗很大。", tip: "汪汪叫的动物" },
    { word: "bird", chinese: "鸟", pronunciation: "/bɜːrd/", example: "A bird can fly. 鸟会飞。", tip: "会飞的小动物" },
    { word: "fish", chinese: "鱼", pronunciation: "/fɪʃ/", example: "Fish live in water. 鱼生活在水中。", tip: "游泳的动物" },
    { word: "pig", chinese: "猪", pronunciation: "/pɪɡ/", example: "The pig is pink. 这只猪是粉色的。", tip: "粉红色的动物" },
    { word: "duck", chinese: "鸭子", pronunciation: "/dʌk/", example: "The duck swims. 鸭子游泳。", tip: "会游泳的鸟" },
    { word: "cow", chinese: "奶牛", pronunciation: "/kaʊ/", example: "Cows give milk. 奶牛产牛奶。", tip: "产奶的动物" },
    { word: "hen", chinese: "母鸡", pronunciation: "/hen/", example: "The hen lays eggs. 母鸡下蛋。", tip: "下蛋的鸟" },
    { word: "bee", chinese: "蜜蜂", pronunciation: "/biː/", example: "Bees make honey. 蜜蜂制造蜂蜜。", tip: "嗡嗡叫的昆虫" },
    { word: "ant", chinese: "蚂蚁", pronunciation: "/ænt/", example: "Ants work hard. 蚂蚁很勤劳。", tip: "很小很勤劳" },
    { word: "frog", chinese: "青蛙", pronunciation: "/frɔːɡ/", example: "Frogs jump high. 青蛙跳得高。", tip: "绿色会跳跃" },
    { word: "bear", chinese: "熊", pronunciation: "/ber/", example: "Bears are big. 熊很大。", tip: "大大的毛茸茸" },
    { word: "lion", chinese: "狮子", pronunciation: "/ˈlaɪən/", example: "Lions are strong. 狮子很强壮。", tip: "森林之王" },
    { word: "tiger", chinese: "老虎", pronunciation: "/ˈtaɪɡər/", example: "Tigers have stripes. 老虎有条纹。", tip: "有黑白条纹" },
    { word: "fox", chinese: "狐狸", pronunciation: "/fɔːks/", example: "The fox is clever. 狐狸很聪明。", tip: "橙色很聪明" },
    { word: "wolf", chinese: "狼", pronunciation: "/wʊlf/", example: "Wolves live together. 狼群居生活。", tip: "会嚎叫的动物" },
    { word: "sheep", chinese: "绵羊", pronunciation: "/ʃiːp/", example: "Sheep have wool. 绵羊有羊毛。", tip: "白色毛茸茸" },
    { word: "goat", chinese: "山羊", pronunciation: "/ɡoʊt/", example: "Goats eat grass. 山羊吃草。", tip: "有胡子的羊" },
    { word: "horse", chinese: "马", pronunciation: "/hɔːrs/", example: "Horses run fast. 马跑得快。", tip: "跑得很快" },
    { word: "mouse", chinese: "老鼠", pronunciation: "/maʊs/", example: "The mouse is small. 老鼠很小。", tip: "很小很快" },
    { word: "rabbit", chinese: "兔子", pronunciation: "/ˈræbɪt/", example: "Rabbits have long ears. 兔子有长耳朵。", tip: "长耳朵白色" },
    { word: "snake", chinese: "蛇", pronunciation: "/sneɪk/", example: "Snakes have no legs. 蛇没有腿。", tip: "长长的爬行" },
    { word: "turtle", chinese: "乌龟", pronunciation: "/ˈtɜːrtl/", example: "Turtles move slowly. 乌龟移动缓慢。", tip: "背着壳很慢" },
    { word: "monkey", chinese: "猴子", pronunciation: "/ˈmʌŋki/", example: "Monkeys like bananas. 猴子喜欢香蕉。", tip: "爱吃香蕉" },
    { word: "panda", chinese: "熊猫", pronunciation: "/ˈpændə/", example: "Pandas are cute. 熊猫很可爱。", tip: "黑白色很可爱" },
    { word: "elephant", chinese: "大象", pronunciation: "/ˈelɪfənt/", example: "Elephants are huge. 大象很巨大。", tip: "长鼻子很大" },
    { word: "giraffe", chinese: "长颈鹿", pronunciation: "/dʒɪˈræf/", example: "Giraffes are tall. 长颈鹿很高。", tip: "脖子很长" },
    { word: "zebra", chinese: "斑马", pronunciation: "/ˈziːbrə/", example: "Zebras have stripes. 斑马有条纹。", tip: "黑白条纹马" },
    { word: "kangaroo", chinese: "袋鼠", pronunciation: "/ˌkæŋɡəˈruː/", example: "Kangaroos jump. 袋鼠跳跃。", tip: "有袋子会跳" },
    { word: "penguin", chinese: "企鹅", pronunciation: "/ˈpeŋɡwɪn/", example: "Penguins swim well. 企鹅游泳很好。", tip: "黑白色会游泳" },

    // 颜色类 (15个)
    { word: "red", chinese: "红色", pronunciation: "/red/", example: "The apple is red. 苹果是红色的。", tip: "像血的颜色" },
    { word: "blue", chinese: "蓝色", pronunciation: "/bluː/", example: "The sky is blue. 天空是蓝色的。", tip: "像天空的颜色" },
    { word: "green", chinese: "绿色", pronunciation: "/ɡriːn/", example: "Grass is green. 草是绿色的。", tip: "像草的颜色" },
    { word: "yellow", chinese: "黄色", pronunciation: "/ˈjeloʊ/", example: "The sun is yellow. 太阳是黄色的。", tip: "像太阳的颜色" },
    { word: "black", chinese: "黑色", pronunciation: "/blæk/", example: "Night is black. 夜晚是黑色的。", tip: "像夜晚的颜色" },
    { word: "white", chinese: "白色", pronunciation: "/waɪt/", example: "Snow is white. 雪是白色的。", tip: "像雪的颜色" },
    { word: "pink", chinese: "粉色", pronunciation: "/pɪŋk/", example: "The flower is pink. 花是粉色的。", tip: "像桃花的颜色" },
    { word: "orange", chinese: "橙色", pronunciation: "/ˈɔːrɪndʒ/", example: "The orange is orange. 橙子是橙色的。", tip: "像橙子的颜色" },
    { word: "purple", chinese: "紫色", pronunciation: "/ˈpɜːrpl/", example: "The grape is purple. 葡萄是紫色的。", tip: "像葡萄的颜色" },
    { word: "brown", chinese: "棕色", pronunciation: "/braʊn/", example: "The bear is brown. 熊是棕色的。", tip: "像土的颜色" },
    { word: "gray", chinese: "灰色", pronunciation: "/ɡreɪ/", example: "The mouse is gray. 老鼠是灰色的。", tip: "黑白混合色" },
    { word: "golden", chinese: "金色", pronunciation: "/ˈɡoʊldən/", example: "The ring is golden. 戒指是金色的。", tip: "像金子的颜色" },
    { word: "silver", chinese: "银色", pronunciation: "/ˈsɪlvər/", example: "The spoon is silver. 勺子是银色的。", tip: "像银子的颜色" },
    { word: "dark", chinese: "深色的", pronunciation: "/dɑːrk/", example: "Dark blue is beautiful. 深蓝色很美。", tip: "颜色很深" },
    { word: "light", chinese: "浅色的", pronunciation: "/laɪt/", example: "Light green is nice. 浅绿色很好。", tip: "颜色很浅" },

    // 数字类 (20个)
    { word: "one", chinese: "一", pronunciation: "/wʌn/", example: "I have one book. 我有一本书。", tip: "第一个数字" },
    { word: "two", chinese: "二", pronunciation: "/tuː/", example: "Two eyes see well. 两只眼睛看得好。", tip: "一双的数量" },
    { word: "three", chinese: "三", pronunciation: "/θriː/", example: "Three birds fly. 三只鸟在飞。", tip: "三角形的数" },
    { word: "four", chinese: "四", pronunciation: "/fɔːr/", example: "Four legs on table. 桌子有四条腿。", tip: "正方形的数" },
    { word: "five", chinese: "五", pronunciation: "/faɪv/", example: "Five fingers on hand. 手有五根手指。", tip: "一只手的数" },
    { word: "six", chinese: "六", pronunciation: "/sɪks/", example: "Six sides on cube. 立方体有六面。", tip: "骰子的最大数" },
    { word: "seven", chinese: "七", pronunciation: "/ˈsevən/", example: "Seven days a week. 一周七天。", tip: "一周的天数" },
    { word: "eight", chinese: "八", pronunciation: "/eɪt/", example: "Eight legs on spider. 蜘蛛有八条腿。", tip: "蜘蛛腿的数" },
    { word: "nine", chinese: "九", pronunciation: "/naɪn/", example: "Nine cats play. 九只猫在玩。", tip: "十减一" },
    { word: "ten", chinese: "十", pronunciation: "/ten/", example: "Ten toes on feet. 脚有十个脚趾。", tip: "两只手的数" },
    { word: "zero", chinese: "零", pronunciation: "/ˈzɪroʊ/", example: "Zero means nothing. 零表示没有。", tip: "什么都没有" },
    { word: "first", chinese: "第一", pronunciation: "/fɜːrst/", example: "I am first in line. 我排第一。", tip: "最前面的" },
    { word: "second", chinese: "第二", pronunciation: "/ˈsekənd/", example: "You are second. 你是第二个。", tip: "紧跟第一" },
    { word: "third", chinese: "第三", pronunciation: "/θɜːrd/", example: "He is third. 他是第三个。", tip: "铜牌的位置" },
    { word: "last", chinese: "最后", pronunciation: "/læst/", example: "She is last. 她是最后一个。", tip: "最后面的" },
    { word: "many", chinese: "许多", pronunciation: "/ˈmeni/", example: "Many books here. 这里有许多书。", tip: "数量很多" },
    { word: "few", chinese: "少数", pronunciation: "/fjuː/", example: "Few people come. 很少人来。", tip: "数量很少" },
    { word: "all", chinese: "全部", pronunciation: "/ɔːl/", example: "All children play. 所有孩子都在玩。", tip: "一个不少" },
    { word: "some", chinese: "一些", pronunciation: "/sʌm/", example: "Some apples are red. 一些苹果是红色的。", tip: "部分数量" },
    { word: "more", chinese: "更多", pronunciation: "/mɔːr/", example: "I want more. 我想要更多。", tip: "数量增加" },

    // 家庭成员 (15个)
    { word: "mom", chinese: "妈妈", pronunciation: "/mɑːm/", example: "Mom loves me. 妈妈爱我。", tip: "最亲的女人" },
    { word: "dad", chinese: "爸爸", pronunciation: "/dæd/", example: "Dad works hard. 爸爸工作很辛苦。", tip: "最亲的男人" },
    { word: "baby", chinese: "婴儿", pronunciation: "/ˈbeɪbi/", example: "The baby cries. 婴儿在哭。", tip: "最小的人" },
    { word: "boy", chinese: "男孩", pronunciation: "/bɔɪ/", example: "The boy runs fast. 男孩跑得快。", tip: "小男生" },
    { word: "girl", chinese: "女孩", pronunciation: "/ɡɜːrl/", example: "The girl sings well. 女孩唱得好。", tip: "小女生" },
    { word: "man", chinese: "男人", pronunciation: "/mæn/", example: "The man is tall. 男人很高。", tip: "成年男性" },
    { word: "woman", chinese: "女人", pronunciation: "/ˈwʊmən/", example: "The woman is kind. 女人很善良。", tip: "成年女性" },
    { word: "child", chinese: "孩子", pronunciation: "/tʃaɪld/", example: "Every child is special. 每个孩子都很特别。", tip: "小朋友" },
    { word: "family", chinese: "家庭", pronunciation: "/ˈfæməli/", example: "I love my family. 我爱我的家庭。", tip: "一起生活的人" },
    { word: "brother", chinese: "兄弟", pronunciation: "/ˈbrʌðər/", example: "My brother is nice. 我的兄弟很好。", tip: "同性别兄弟" },
    { word: "sister", chinese: "姐妹", pronunciation: "/ˈsɪstər/", example: "My sister helps me. 我的姐妹帮助我。", tip: "同性别姐妹" },
    { word: "friend", chinese: "朋友", pronunciation: "/frend/", example: "Friends play together. 朋友一起玩。", tip: "一起玩的人" },
    { word: "people", chinese: "人们", pronunciation: "/ˈpiːpl/", example: "People are nice. 人们很好。", tip: "很多人" },
    { word: "name", chinese: "名字", pronunciation: "/neɪm/", example: "My name is Tom. 我的名字是汤姆。", tip: "叫什么" },
    { word: "age", chinese: "年龄", pronunciation: "/eɪdʒ/", example: "My age is seven. 我七岁了。", tip: "多少岁" },

    // 身体部位 (20个)
    { word: "head", chinese: "头", pronunciation: "/hed/", example: "My head is round. 我的头是圆的。", tip: "最上面的部分" },
    { word: "face", chinese: "脸", pronunciation: "/feɪs/", example: "Your face is pretty. 你的脸很漂亮。", tip: "头的前面" },
    { word: "eye", chinese: "眼睛", pronunciation: "/aɪ/", example: "Eyes can see. 眼睛能看见。", tip: "用来看的器官" },
    { word: "nose", chinese: "鼻子", pronunciation: "/noʊz/", example: "My nose smells flowers. 我的鼻子闻花香。", tip: "用来闻的器官" },
    { word: "mouth", chinese: "嘴巴", pronunciation: "/maʊθ/", example: "Open your mouth. 张开你的嘴巴。", tip: "用来吃说的器官" },
    { word: "ear", chinese: "耳朵", pronunciation: "/ɪr/", example: "Ears can hear. 耳朵能听见。", tip: "用来听的器官" },
    { word: "hair", chinese: "头发", pronunciation: "/her/", example: "Her hair is long. 她的头发很长。", tip: "头上长的丝" },
    { word: "hand", chinese: "手", pronunciation: "/hænd/", example: "Hands can hold. 手能拿东西。", tip: "用来拿的器官" },
    { word: "arm", chinese: "胳膊", pronunciation: "/ɑːrm/", example: "Strong arms lift box. 强壮的胳膊举箱子。", tip: "连接手的部分" },
    { word: "leg", chinese: "腿", pronunciation: "/leɡ/", example: "Legs help us walk. 腿帮助我们走路。", tip: "用来走的器官" },
    { word: "foot", chinese: "脚", pronunciation: "/fʊt/", example: "Two feet stand firm. 两只脚站得稳。", tip: "用来站的器官" },
    { word: "finger", chinese: "手指", pronunciation: "/ˈfɪŋɡər/", example: "Five fingers on hand. 手上有五根手指。", tip: "手上的小分支" },
    { word: "toe", chinese: "脚趾", pronunciation: "/toʊ/", example: "Ten toes on feet. 脚上有十个脚趾。", tip: "脚上的小分支" },
    { word: "knee", chinese: "膝盖", pronunciation: "/niː/", example: "Knee bends when walk. 走路时膝盖弯曲。", tip: "腿中间的关节" },
    { word: "back", chinese: "背部", pronunciation: "/bæk/", example: "My back is strong. 我的背部很强壮。", tip: "身体后面" },
    { word: "neck", chinese: "脖子", pronunciation: "/nek/", example: "Neck connects head. 脖子连接头部。", tip: "连接头的部分" },
    { word: "shoulder", chinese: "肩膀", pronunciation: "/ˈʃoʊldər/", example: "Shoulders carry bags. 肩膀背包。", tip: "胳膊连接的地方" },
    { word: "chest", chinese: "胸部", pronunciation: "/tʃest/", example: "Chest breathes air. 胸部呼吸空气。", tip: "心脏的位置" },
    { word: "belly", chinese: "肚子", pronunciation: "/ˈbeli/", example: "Full belly is happy. 饱肚子很开心。", tip: "吃东西的地方" },
    { word: "skin", chinese: "皮肤", pronunciation: "/skɪn/", example: "Skin protects body. 皮肤保护身体。", tip: "身体的外衣" },

    // 日常用品 (25个)
    { word: "book", chinese: "书", pronunciation: "/bʊk/", example: "I read a book. 我读一本书。", tip: "知识的载体" },
    { word: "pen", chinese: "钢笔", pronunciation: "/pen/", example: "Write with a pen. 用钢笔写字。", tip: "写字的工具" },
    { word: "bag", chinese: "包", pronunciation: "/bæɡ/", example: "Put books in bag. 把书放进包里。", tip: "装东西的容器" },
    { word: "cup", chinese: "杯子", pronunciation: "/kʌp/", example: "Drink from a cup. 用杯子喝水。", tip: "喝水的容器" },
    { word: "ball", chinese: "球", pronunciation: "/bɔːl/", example: "Kick the ball. 踢球。", tip: "圆圆的玩具" },
    { word: "toy", chinese: "玩具", pronunciation: "/tɔɪ/", example: "Children love toys. 孩子们喜欢玩具。", tip: "用来玩的东西" },
    { word: "box", chinese: "盒子", pronunciation: "/bɑːks/", example: "Put toys in box. 把玩具放进盒子。", tip: "方形的容器" },
    { word: "hat", chinese: "帽子", pronunciation: "/hæt/", example: "Wear a hat. 戴帽子。", tip: "戴在头上的" },
    { word: "coat", chinese: "外套", pronunciation: "/koʊt/", example: "Warm coat in winter. 冬天穿暖外套。", tip: "保暖的衣服" },
    { word: "shoe", chinese: "鞋子", pronunciation: "/ʃuː/", example: "Shoes protect feet. 鞋子保护脚。", tip: "穿在脚上的" },
    { word: "bed", chinese: "床", pronunciation: "/bed/", example: "Sleep in the bed. 在床上睡觉。", tip: "睡觉的地方" },
    { word: "chair", chinese: "椅子", pronunciation: "/tʃer/", example: "Sit on the chair. 坐在椅子上。", tip: "坐着的家具" },
    { word: "table", chinese: "桌子", pronunciation: "/ˈteɪbl/", example: "Eat at the table. 在桌子上吃饭。", tip: "平面的家具" },
    { word: "door", chinese: "门", pronunciation: "/dɔːr/", example: "Open the door. 开门。", tip: "进出的通道" },
    { word: "window", chinese: "窗户", pronunciation: "/ˈwɪndoʊ/", example: "Look through window. 透过窗户看。", tip: "透明的开口" },
    { word: "car", chinese: "汽车", pronunciation: "/kɑːr/", example: "Drive a car. 开车。", tip: "四轮的交通工具" },
    { word: "bike", chinese: "自行车", pronunciation: "/baɪk/", example: "Ride a bike. 骑自行车。", tip: "两轮的交通工具" },
    { word: "clock", chinese: "时钟", pronunciation: "/klɑːk/", example: "Clock shows time. 时钟显示时间。", tip: "看时间的工具" },
    { word: "phone", chinese: "电话", pronunciation: "/foʊn/", example: "Call on the phone. 打电话。", tip: "通话的工具" },
    { word: "key", chinese: "钥匙", pronunciation: "/kiː/", example: "Key opens door. 钥匙开门。", tip: "开锁的工具" },
    { word: "light", chinese: "灯", pronunciation: "/laɪt/", example: "Turn on the light. 开灯。", tip: "照明的工具" },
    { word: "camera", chinese: "照相机", pronunciation: "/ˈkæmərə/", example: "Take photos with camera. 用照相机拍照。", tip: "拍照的工具" },
    { word: "mirror", chinese: "镜子", pronunciation: "/ˈmɪrər/", example: "Look in the mirror. 照镜子。", tip: "看自己的工具" },
    { word: "brush", chinese: "刷子", pronunciation: "/brʌʃ/", example: "Brush your teeth. 刷牙。", tip: "清洁的工具" },
    { word: "soap", chinese: "肥皂", pronunciation: "/soʊp/", example: "Wash hands with soap. 用肥皂洗手。", tip: "清洁的用品" },

    // 食物类 (20个)
    { word: "apple", chinese: "苹果", pronunciation: "/ˈæpl/", example: "Eat a red apple. 吃一个红苹果。", tip: "红色圆形水果" },
    { word: "banana", chinese: "香蕉", pronunciation: "/bəˈnænə/", example: "Yellow banana is sweet. 黄色香蕉很甜。", tip: "黄色弯曲水果" },
    { word: "orange", chinese: "橙子", pronunciation: "/ˈɔːrɪndʒ/", example: "Orange is juicy. 橙子很多汁。", tip: "橙色圆形水果" },
    { word: "grape", chinese: "葡萄", pronunciation: "/ɡreɪp/", example: "Purple grapes are sweet. 紫色葡萄很甜。", tip: "成串的小果实" },
    { word: "bread", chinese: "面包", pronunciation: "/bred/", example: "Eat bread for breakfast. 早餐吃面包。", tip: "发酵的主食" },
    { word: "milk", chinese: "牛奶", pronunciation: "/mɪlk/", example: "Drink fresh milk. 喝新鲜牛奶。", tip: "白色的饮品" },
    { word: "water", chinese: "水", pronunciation: "/ˈwɔːtər/", example: "Water is important. 水很重要。", tip: "生命之源" },
    { word: "juice", chinese: "果汁", pronunciation: "/dʒuːs/", example: "Orange juice is tasty. 橙汁很好喝。", tip: "水果榨的液体" },
    { word: "cake", chinese: "蛋糕", pronunciation: "/keɪk/", example: "Birthday cake is sweet. 生日蛋糕很甜。", tip: "庆祝用的甜品" },
    { word: "cookie", chinese: "饼干", pronunciation: "/ˈkʊki/", example: "Cookies are crunchy. 饼干很脆。", tip: "小小的零食" },
    { word: "egg", chinese: "鸡蛋", pronunciation: "/eɡ/", example: "Eggs are nutritious. 鸡蛋很有营养。", tip: "鸡下的圆形食物" },
    { word: "meat", chinese: "肉", pronunciation: "/miːt/", example: "Meat gives protein. 肉提供蛋白质。", tip: "动物身上的食物" },
    { word: "rice", chinese: "米饭", pronunciation: "/raɪs/", example: "Rice is staple food. 米饭是主食。", tip: "白色的主食" },
    { word: "fish", chinese: "鱼肉", pronunciation: "/fɪʃ/", example: "Fish is healthy. 鱼肉很健康。", tip: "游泳动物的肉" },
    { word: "soup", chinese: "汤", pronunciation: "/suːp/", example: "Hot soup warms body. 热汤暖身体。", tip: "液体的食物" },
    { word: "salad", chinese: "沙拉", pronunciation: "/ˈsæləd/", example: "Green salad is fresh. 绿色沙拉很新鲜。", tip: "混合的蔬菜" },
    { word: "pizza", chinese: "披萨", pronunciation: "/ˈpiːtsə/", example: "Pizza has cheese. 披萨有奶酪。", tip: "圆形的意式食物" },
    { word: "candy", chinese: "糖果", pronunciation: "/ˈkændi/", example: "Candy is very sweet. 糖果很甜。", tip: "很甜的零食" },
    { word: "ice cream", chinese: "冰淇淋", pronunciation: "/ˈaɪs ˌkriːm/", example: "Ice cream is cold. 冰淇淋很凉。", tip: "冷冻的甜品" },
    { word: "chocolate", chinese: "巧克力", pronunciation: "/ˈtʃɔːklət/", example: "Chocolate is delicious. 巧克力很美味。", tip: "棕色的甜食" },

    // 基础动词 (30个)
    { word: "go", chinese: "去", pronunciation: "/ɡoʊ/", example: "I go to school. 我去学校。", tip: "移动到某处" },
    { word: "come", chinese: "来", pronunciation: "/kʌm/", example: "Come here please. 请过来。", tip: "移动到这里" },
    { word: "see", chinese: "看见", pronunciation: "/siː/", example: "I see a bird. 我看见一只鸟。", tip: "用眼睛观察" },
    { word: "look", chinese: "看", pronunciation: "/lʊk/", example: "Look at me. 看着我。", tip: "用眼睛注视" },
    { word: "hear", chinese: "听见", pronunciation: "/hɪr/", example: "I hear music. 我听见音乐。", tip: "用耳朵感知" },
    { word: "eat", chinese: "吃", pronunciation: "/iːt/", example: "Eat your dinner. 吃你的晚餐。", tip: "用嘴巴进食" },
    { word: "drink", chinese: "喝", pronunciation: "/drɪŋk/", example: "Drink some water. 喝点水。", tip: "用嘴巴饮用" },
    { word: "sleep", chinese: "睡觉", pronunciation: "/sliːp/", example: "Sleep well tonight. 今晚睡个好觉。", tip: "闭眼休息" },
    { word: "wake", chinese: "醒来", pronunciation: "/weɪk/", example: "Wake up early. 早点醒来。", tip: "从睡眠中清醒" },
    { word: "walk", chinese: "走路", pronunciation: "/wɔːk/", example: "Walk to school. 走路去学校。", tip: "用脚移动" },
    { word: "run", chinese: "跑", pronunciation: "/rʌn/", example: "Run very fast. 跑得很快。", tip: "快速移动" },
    { word: "jump", chinese: "跳", pronunciation: "/dʒʌmp/", example: "Jump up high. 跳得很高。", tip: "向上弹起" },
    { word: "sit", chinese: "坐", pronunciation: "/sɪt/", example: "Sit on chair. 坐在椅子上。", tip: "屁股着地" },
    { word: "stand", chinese: "站", pronunciation: "/stænd/", example: "Stand up straight. 直直地站着。", tip: "用脚支撑" },
    { word: "play", chinese: "玩", pronunciation: "/pleɪ/", example: "Play with friends. 和朋友玩。", tip: "娱乐活动" },
    { word: "work", chinese: "工作", pronunciation: "/wɜːrk/", example: "Dad works hard. 爸爸努力工作。", tip: "做事情赚钱" },
    { word: "study", chinese: "学习", pronunciation: "/ˈstʌdi/", example: "Study English hard. 努力学习英语。", tip: "获取知识" },
    { word: "read", chinese: "读", pronunciation: "/riːd/", example: "Read a good book. 读一本好书。", tip: "看文字内容" },
    { word: "write", chinese: "写", pronunciation: "/raɪt/", example: "Write your name. 写你的名字。", tip: "用笔记录" },
    { word: "draw", chinese: "画", pronunciation: "/drɔː/", example: "Draw a picture. 画一幅画。", tip: "用笔创作" },
    { word: "sing", chinese: "唱歌", pronunciation: "/sɪŋ/", example: "Sing a happy song. 唱一首快乐的歌。", tip: "发出音乐声" },
    { word: "dance", chinese: "跳舞", pronunciation: "/dæns/", example: "Dance to music. 随着音乐跳舞。", tip: "有节奏地移动" },
    { word: "swim", chinese: "游泳", pronunciation: "/swɪm/", example: "Swim in the pool. 在池子里游泳。", tip: "在水中移动" },
    { word: "fly", chinese: "飞", pronunciation: "/flaɪ/", example: "Birds fly high. 鸟儿飞得高。", tip: "在空中移动" },
    { word: "drive", chinese: "开车", pronunciation: "/draɪv/", example: "Drive the car. 开车。", tip: "控制车辆" },
    { word: "ride", chinese: "骑", pronunciation: "/raɪd/", example: "Ride a bike. 骑自行车。", tip: "坐在上面移动" },
    { word: "open", chinese: "打开", pronunciation: "/ˈoʊpən/", example: "Open the door. 打开门。", tip: "使变成开启状态" },
    { word: "close", chinese: "关闭", pronunciation: "/kloʊz/", example: "Close your eyes. 闭上眼睛。", tip: "使变成关闭状态" },
    { word: "give", chinese: "给", pronunciation: "/ɡɪv/", example: "Give me the book. 把书给我。", tip: "传递给别人" },
    { word: "take", chinese: "拿", pronunciation: "/teɪk/", example: "Take this apple. 拿这个苹果。", tip: "用手获取" },

    // 基础形容词 (25个)
    { word: "big", chinese: "大的", pronunciation: "/bɪɡ/", example: "The elephant is big. 大象很大。", tip: "尺寸很大" },
    { word: "small", chinese: "小的", pronunciation: "/smɔːl/", example: "The ant is small. 蚂蚁很小。", tip: "尺寸很小" },
    { word: "long", chinese: "长的", pronunciation: "/lɔːŋ/", example: "The snake is long. 蛇很长。", tip: "长度很长" },
    { word: "short", chinese: "短的", pronunciation: "/ʃɔːrt/", example: "My hair is short. 我的头发很短。", tip: "长度很短" },
    { word: "tall", chinese: "高的", pronunciation: "/tɔːl/", example: "The tree is tall. 树很高。", tip: "高度很高" },
    { word: "fat", chinese: "胖的", pronunciation: "/fæt/", example: "The pig is fat. 猪很胖。", tip: "身体很圆" },
    { word: "thin", chinese: "瘦的", pronunciation: "/θɪn/", example: "The pencil is thin. 铅笔很细。", tip: "身体很细" },
    { word: "hot", chinese: "热的", pronunciation: "/hɑːt/", example: "Summer is hot. 夏天很热。", tip: "温度很高" },
    { word: "cold", chinese: "冷的", pronunciation: "/koʊld/", example: "Winter is cold. 冬天很冷。", tip: "温度很低" },
    { word: "warm", chinese: "温暖的", pronunciation: "/wɔːrm/", example: "Spring is warm. 春天很温暖。", tip: "温度刚好" },
    { word: "cool", chinese: "凉爽的", pronunciation: "/kuːl/", example: "Autumn is cool. 秋天很凉爽。", tip: "温度适中" },
    { word: "happy", chinese: "快乐的", pronunciation: "/ˈhæpi/", example: "I am happy. 我很快乐。", tip: "心情很好" },
    { word: "sad", chinese: "伤心的", pronunciation: "/sæd/", example: "Don't be sad. 不要伤心。", tip: "心情不好" },
    { word: "good", chinese: "好的", pronunciation: "/ɡʊd/", example: "This is good. 这很好。", tip: "质量很棒" },
    { word: "bad", chinese: "坏的", pronunciation: "/bæd/", example: "That is bad. 那很坏。", tip: "质量很差" },
    { word: "new", chinese: "新的", pronunciation: "/nuː/", example: "I have new shoes. 我有新鞋子。", tip: "刚买的" },
    { word: "old", chinese: "旧的", pronunciation: "/oʊld/", example: "This book is old. 这本书很旧。", tip: "用了很久" },
    { word: "fast", chinese: "快的", pronunciation: "/fæst/", example: "The car is fast. 汽车很快。", tip: "速度很高" },
    { word: "slow", chinese: "慢的", pronunciation: "/sloʊ/", example: "The turtle is slow. 乌龟很慢。", tip: "速度很低" },
    { word: "strong", chinese: "强壮的", pronunciation: "/strɔːŋ/", example: "The man is strong. 男人很强壮。", tip: "力气很大" },
    { word: "weak", chinese: "虚弱的", pronunciation: "/wiːk/", example: "The baby is weak. 婴儿很虚弱。", tip: "力气很小" },
    { word: "clean", chinese: "干净的", pronunciation: "/kliːn/", example: "My hands are clean. 我的手很干净。", tip: "没有脏东西" },
    { word: "dirty", chinese: "脏的", pronunciation: "/ˈdɜːrti/", example: "The floor is dirty. 地板很脏。", tip: "有脏东西" },
    { word: "beautiful", chinese: "美丽的", pronunciation: "/ˈbjuːtɪfl/", example: "The flower is beautiful. 花很美丽。", tip: "看起来很好" },
    { word: "ugly", chinese: "丑的", pronunciation: "/ˈʌɡli/", example: "The monster is ugly. 怪物很丑。", tip: "看起来很差" }
  ],

  2: [
    // 2年级 - 日常活动和基础概念 (200个)
    
    // 学校相关 (25个)
    { word: "school", chinese: "学校", pronunciation: "/skuːl/", example: "I go to school every day. 我每天去学校。", tip: "学习的地方" },
    { word: "teacher", chinese: "老师", pronunciation: "/ˈtiːtʃər/", example: "My teacher is kind. 我的老师很善良。", tip: "教知识的人" },
    { word: "student", chinese: "学生", pronunciation: "/ˈstuːdənt/", example: "I am a good student. 我是一个好学生。", tip: "学习的人" },
    { word: "class", chinese: "班级", pronunciation: "/klæs/", example: "Our class has 30 students. 我们班有30个学生。", tip: "一起学习的群体" },
    { word: "classroom", chinese: "教室", pronunciation: "/ˈklæsruːm/", example: "The classroom is big. 教室很大。", tip: "上课的房间" },
    { word: "lesson", chinese: "课程", pronunciation: "/ˈlesən/", example: "English lesson is fun. 英语课很有趣。", tip: "学习的内容" },
    { word: "homework", chinese: "家庭作业", pronunciation: "/ˈhoʊmwɜːrk/", example: "Do homework carefully. 认真做作业。", tip: "回家要做的学习任务" },
    { word: "test", chinese: "测试", pronunciation: "/test/", example: "We have a test tomorrow. 我们明天有测试。", tip: "检查学习效果" },
    { word: "grade", chinese: "年级", pronunciation: "/ɡreɪd/", example: "I'm in second grade. 我在二年级。", tip: "学习的阶段" },
    { word: "subject", chinese: "科目", pronunciation: "/ˈsʌbdʒɪkt/", example: "Math is my favorite subject. 数学是我最喜欢的科目。", tip: "学习的内容分类" },
    { word: "math", chinese: "数学", pronunciation: "/mæθ/", example: "Math helps us count. 数学帮我们计算。", tip: "学习数字的科目" },
    { word: "science", chinese: "科学", pronunciation: "/ˈsaɪəns/", example: "Science explains nature. 科学解释自然。", tip: "研究世界的科目" },
    { word: "art", chinese: "艺术", pronunciation: "/ɑːrt/", example: "I love art class. 我喜欢艺术课。", tip: "创作美的科目" },
    { word: "music", chinese: "音乐", pronunciation: "/ˈmjuːzɪk/", example: "Music makes me happy. 音乐让我快乐。", tip: "声音的艺术" },
    { word: "PE", chinese: "体育", pronunciation: "/ˌpiː ˈiː/", example: "PE class is exciting. 体育课很刺激。", tip: "锻炼身体的课" },
    { word: "library", chinese: "图书馆", pronunciation: "/ˈlaɪbreri/", example: "Read books in library. 在图书馆读书。", tip: "很多书的地方" },
    { word: "playground", chinese: "操场", pronunciation: "/ˈpleɪɡraʊnd/", example: "Play games on playground. 在操场玩游戏。", tip: "运动游戏的地方" },
    { word: "desk", chinese: "课桌", pronunciation: "/desk/", example: "My desk is clean. 我的课桌很干净。", tip: "学习用的桌子" },
    { word: "blackboard", chinese: "黑板", pronunciation: "/ˈblækbɔːrd/", example: "Write on the blackboard. 在黑板上写字。", tip: "老师写字的板子" },
    { word: "pencil", chinese: "铅笔", pronunciation: "/ˈpensl/", example: "Write with a pencil. 用铅笔写字。", tip: "木头做的写字工具" },
    { word: "eraser", chinese: "橡皮", pronunciation: "/ɪˈreɪsər/", example: "Erase mistakes with eraser. 用橡皮擦错误。", tip: "擦除的工具" },
    { word: "ruler", chinese: "尺子", pronunciation: "/ˈruːlər/", example: "Measure with a ruler. 用尺子测量。", tip: "测量长度的工具" },
    { word: "notebook", chinese: "笔记本", pronunciation: "/ˈnoʊtbʊk/", example: "Write notes in notebook. 在笔记本里写笔记。", tip: "记录的本子" },
    { word: "crayon", chinese: "蜡笔", pronunciation: "/ˈkreɪən/", example: "Color with crayons. 用蜡笔涂色。", tip: "彩色的画笔" },
    { word: "scissors", chinese: "剪刀", pronunciation: "/ˈsɪzərz/", example: "Cut paper with scissors. 用剪刀剪纸。", tip: "剪切的工具" },

    // 时间相关 (20个)
    { word: "time", chinese: "时间", pronunciation: "/taɪm/", example: "What time is it? 现在几点了？", tip: "流逝的概念" },
    { word: "day", chinese: "天", pronunciation: "/deɪ/", example: "Today is a good day. 今天是美好的一天。", tip: "24小时的时间" },
    { word: "night", chinese: "夜晚", pronunciation: "/naɪt/", example: "Sleep at night. 晚上睡觉。", tip: "黑暗的时间" },
    { word: "morning", chinese: "早晨", pronunciation: "/ˈmɔːrnɪŋ/", example: "Good morning! 早上好！", tip: "太阳升起的时间" },
    { word: "afternoon", chinese: "下午", pronunciation: "/ˌæftərˈnuːn/", example: "Play in the afternoon. 下午玩耍。", tip: "中午后的时间" },
    { word: "evening", chinese: "傍晚", pronunciation: "/ˈiːvnɪŋ/", example: "Dinner in the evening. 傍晚吃晚餐。", tip: "太阳落下的时间" },
    { word: "today", chinese: "今天", pronunciation: "/təˈdeɪ/", example: "Today is Monday. 今天是星期一。", tip: "现在这一天" },
    { word: "tomorrow", chinese: "明天", pronunciation: "/təˈmɑːroʊ/", example: "Go swimming tomorrow. 明天去游泳。", tip: "今天的下一天" },
    { word: "yesterday", chinese: "昨天", pronunciation: "/ˈjestərdeɪ/", example: "Yesterday was fun. 昨天很有趣。", tip: "今天的前一天" },
    { word: "week", chinese: "星期", pronunciation: "/wiːk/", example: "Seven days make a week. 七天组成一星期。", tip: "七天的时间" },
    { word: "month", chinese: "月份", pronunciation: "/mʌnθ/", example: "January is the first month. 一月是第一个月。", tip: "一年的十二分之一" },
    { word: "year", chinese: "年", pronunciation: "/jɪr/", example: "Happy New Year! 新年快乐！", tip: "365天的时间" },
    { word: "hour", chinese: "小时", pronunciation: "/ˈaʊər/", example: "One hour has 60 minutes. 一小时有60分钟。", tip: "60分钟的时间" },
    { word: "minute", chinese: "分钟", pronunciation: "/ˈmɪnɪt/", example: "Wait a minute. 等一分钟。", tip: "60秒的时间" },
    { word: "second", chinese: "秒", pronunciation: "/ˈsekənd/", example: "Count to ten seconds. 数到十秒。", tip: "最小的时间单位" },
    { word: "Monday", chinese: "星期一", pronunciation: "/ˈmʌndeɪ/", example: "Monday is school day. 星期一是上学日。", tip: "一周的第一天" },
    { word: "Tuesday", chinese: "星期二", pronunciation: "/ˈtuːzdeɪ/", example: "Tuesday comes after Monday. 星期二在星期一之后。", tip: "一周的第二天" },
    { word: "Wednesday", chinese: "星期三", pronunciation: "/ˈwenzdeɪ/", example: "Wednesday is in the middle. 星期三在中间。", tip: "一周的中间" },
    { word: "Thursday", chinese: "星期四", pronunciation: "/ˈθɜːrzdeɪ/", example: "Thursday is almost weekend. 星期四快到周末了。", tip: "接近周末" },
    { word: "Friday", chinese: "星期五", pronunciation: "/ˈfraɪdeɪ/", example: "Friday is the last school day. 星期五是最后一个上学日。", tip: "工作日的最后一天" },

    // 天气相关 (15个)
    { word: "weather", chinese: "天气", pronunciation: "/ˈweðər/", example: "The weather is nice. 天气很好。", tip: "外面的状况" },
    { word: "sunny", chinese: "晴朗的", pronunciation: "/ˈsʌni/", example: "It's sunny today. 今天很晴朗。", tip: "有太阳的天气" },
    { word: "rainy", chinese: "下雨的", pronunciation: "/ˈreɪni/", example: "It's rainy outside. 外面在下雨。", tip: "有雨的天气" },
    { word: "cloudy", chinese: "多云的", pronunciation: "/ˈklaʊdi/", example: "The sky is cloudy. 天空多云。", tip: "有云的天气" },
    { word: "windy", chinese: "有风的", pronunciation: "/ˈwɪndi/", example: "It's very windy. 风很大。", tip: "有风的天气" },
    { word: "snowy", chinese: "下雪的", pronunciation: "/ˈsnoʊi/", example: "It's snowy in winter. 冬天下雪。", tip: "有雪的天气" },
    { word: "sun", chinese: "太阳", pronunciation: "/sʌn/", example: "The sun is bright. 太阳很亮。", tip: "天空中的火球" },
    { word: "moon", chinese: "月亮", pronunciation: "/muːn/", example: "The moon shines at night. 月亮在夜晚发光。", tip: "夜空中的圆盘" },
    { word: "star", chinese: "星星", pronunciation: "/stɑːr/", example: "Stars twinkle in sky. 星星在天空闪烁。", tip: "夜空中的光点" },
    { word: "cloud", chinese: "云", pronunciation: "/klaʊd/", example: "White clouds float. 白云飘浮。", tip: "天空中的白色团块" },
    { word: "rain", chinese: "雨", pronunciation: "/reɪn/", example: "Rain falls from sky. 雨从天空落下。", tip: "从天空掉下的水" },
    { word: "snow", chinese: "雪", pronunciation: "/snoʊ/", example: "Snow is white and cold. 雪是白色和冷的。", tip: "冬天的白色降水" },
    { word: "wind", chinese: "风", pronunciation: "/wɪnd/", example: "Wind blows the leaves. 风吹树叶。", tip: "空气的流动" },
    { word: "rainbow", chinese: "彩虹", pronunciation: "/ˈreɪnboʊ/", example: "Rainbow has seven colors. 彩虹有七种颜色。", tip: "雨后的彩色弧形" },
    { word: "storm", chinese: "暴风雨", pronunciation: "/stɔːrm/", example: "The storm is coming. 暴风雨要来了。", tip: "很强的风雨" },

    // 地点类 (25个)
    { word: "home", chinese: "家", pronunciation: "/hoʊm/", example: "I love my home. 我爱我的家。", tip: "居住的地方" },
    { word: "house", chinese: "房子", pronunciation: "/haʊs/", example: "My house is big. 我的房子很大。", tip: "居住的建筑" },
    { word: "room", chinese: "房间", pronunciation: "/ruːm/", example: "My room is clean. 我的房间很干净。", tip: "房子内的空间" },
    { word: "kitchen", chinese: "厨房", pronunciation: "/ˈkɪtʃən/", example: "Cook food in kitchen. 在厨房做饭。", tip: "做饭的房间" },
    { word: "bathroom", chinese: "浴室", pronunciation: "/ˈbæθruːm/", example: "Wash hands in bathroom. 在浴室洗手。", tip: "洗澡的房间" },
    { word: "bedroom", chinese: "卧室", pronunciation: "/ˈbedruːm/", example: "Sleep in the bedroom. 在卧室睡觉。", tip: "睡觉的房间" },
    { word: "living room", chinese: "客厅", pronunciation: "/ˈlɪvɪŋ ruːm/", example: "Watch TV in living room. 在客厅看电视。", tip: "家人聚集的房间" },
    { word: "garden", chinese: "花园", pronunciation: "/ˈɡɑːrdn/", example: "Flowers grow in garden. 花在花园里生长。", tip: "种植物的地方" },
    { word: "park", chinese: "公园", pronunciation: "/pɑːrk/", example: "Play in the park. 在公园玩。", tip: "公共的游玩地" },
    { word: "zoo", chinese: "动物园", pronunciation: "/zuː/", example: "See animals at zoo. 在动物园看动物。", tip: "展示动物的地方" },
    { word: "shop", chinese: "商店", pronunciation: "/ʃɑːp/", example: "Buy things at shop. 在商店买东西。", tip: "购买物品的地方" },
    { word: "market", chinese: "市场", pronunciation: "/ˈmɑːrkɪt/", example: "Buy food at market. 在市场买食物。", tip: "买卖商品的地方" },
    { word: "hospital", chinese: "医院", pronunciation: "/ˈhɑːspɪtl/", example: "Doctor works in hospital. 医生在医院工作。", tip: "治病的地方" },
    { word: "bank", chinese: "银行", pronunciation: "/bæŋk/", example: "Save money in bank. 在银行存钱。", tip: "存钱的地方" },
    { word: "post office", chinese: "邮局", pronunciation: "/poʊst ˈɔːfɪs/", example: "Send letters at post office. 在邮局寄信。", tip: "寄信的地方" },
    { word: "restaurant", chinese: "餐厅", pronunciation: "/ˈrestərɑːnt/", example: "Eat dinner at restaurant. 在餐厅吃晚餐。", tip: "吃饭的地方" },
    { word: "street", chinese: "街道", pronunciation: "/striːt/", example: "Cars drive on street. 汽车在街道上行驶。", tip: "城市的道路" },
    { word: "road", chinese: "公路", pronunciation: "/roʊd/", example: "The road is long. 公路很长。", tip: "连接地方的通道" },
    { word: "bridge", chinese: "桥", pronunciation: "/brɪdʒ/", example: "Cross the river by bridge. 通过桥过河。", tip: "跨越河流的建筑" },
    { word: "farm", chinese: "农场", pronunciation: "/fɑːrm/", example: "Animals live on farm. 动物住在农场。", tip: "种植养殖的地方" },
    { word: "forest", chinese: "森林", pronunciation: "/ˈfɔːrɪst/", example: "Many trees in forest. 森林里有很多树。", tip: "很多树的地方" },
    { word: "mountain", chinese: "山", pronunciation: "/ˈmaʊntən/", example: "The mountain is high. 山很高。", tip: "很高的土地" },
    { word: "river", chinese: "河流", pronunciation: "/ˈrɪvər/", example: "Fish swim in river. 鱼在河里游泳。", tip: "流动的水" },
    { word: "lake", chinese: "湖", pronunciation: "/leɪk/", example: "The lake is calm. 湖水很平静。", tip: "大片的静水" },
    { word: "beach", chinese: "海滩", pronunciation: "/biːtʃ/", example: "Play on the beach. 在海滩玩耍。", tip: "海边的沙地" },

    // 交通工具 (15个)
    { word: "bus", chinese: "公共汽车", pronunciation: "/bʌs/", example: "Take bus to school. 坐公交车去学校。", tip: "载很多人的车" },
    { word: "train", chinese: "火车", pronunciation: "/treɪn/", example: "The train is fast. 火车很快。", tip: "在轨道上跑的车" },
    { word: "plane", chinese: "飞机", pronunciation: "/pleɪn/", example: "Planes fly in sky. 飞机在天空飞。", tip: "在天空飞的交通工具" },
    { word: "ship", chinese: "轮船", pronunciation: "/ʃɪp/", example: "Ships sail on water. 轮船在水上航行。", tip: "在水上行驶的大船" },
    { word: "boat", chinese: "小船", pronunciation: "/boʊt/", example: "Row the small boat. 划小船。", tip: "在水上的小交通工具" },
    { word: "taxi", chinese: "出租车", pronunciation: "/ˈtæksi/", example: "Call a taxi. 叫出租车。", tip: "付钱乘坐的车" },
    { word: "truck", chinese: "卡车", pronunciation: "/trʌk/", example: "Truck carries heavy things. 卡车运重物。", tip: "运货的大车" },
    { word: "motorcycle", chinese: "摩托车", pronunciation: "/ˈmoʊtərsaɪkl/", example: "Ride a motorcycle. 骑摩托车。", tip: "两轮的机动车" },
    { word: "subway", chinese: "地铁", pronunciation: "/ˈsʌbweɪ/", example: "Take subway in city. 在城市坐地铁。", tip: "地下的火车" },
    { word: "helicopter", chinese: "直升机", pronunciation: "/ˈhelɪkɑːptər/", example: "Helicopter can hover. 直升机能悬停。", tip: "有螺旋桨的飞机" },
    { word: "rocket", chinese: "火箭", pronunciation: "/ˈrɑːkɪt/", example: "Rocket flies to space. 火箭飞向太空。", tip: "飞向太空的工具" },
    { word: "wheel", chinese: "轮子", pronunciation: "/wiːl/", example: "Car has four wheels. 汽车有四个轮子。", tip: "圆形会转的部件" },
    { word: "engine", chinese: "发动机", pronunciation: "/ˈendʒɪn/", example: "Engine makes car move. 发动机让汽车移动。", tip: "提供动力的机器" },
    { word: "traffic", chinese: "交通", pronunciation: "/ˈtræfɪk/", example: "Heavy traffic on road. 路上交通繁忙。", tip: "道路上的车流" },
    { word: "station", chinese: "车站", pronunciation: "/ˈsteɪʃən/", example: "Wait at the station. 在车站等车。", tip: "车辆停靠的地方" },

    // 动作动词 (30个)
    { word: "help", chinese: "帮助", pronunciation: "/help/", example: "Help your friends. 帮助你的朋友。", tip: "为别人做事" },
    { word: "love", chinese: "爱", pronunciation: "/lʌv/", example: "I love my family. 我爱我的家人。", tip: "很喜欢的感情" },
    { word: "like", chinese: "喜欢", pronunciation: "/laɪk/", example: "I like ice cream. 我喜欢冰淇淋。", tip: "觉得好的感觉" },
    { word: "want", chinese: "想要", pronunciation: "/wɑːnt/", example: "I want a toy. 我想要一个玩具。", tip: "希望得到" },
    { word: "need", chinese: "需要", pronunciation: "/niːd/", example: "I need water. 我需要水。", tip: "必须要有" },
    { word: "have", chinese: "有", pronunciation: "/hæv/", example: "I have a book. 我有一本书。", tip: "拥有某物" },
    { word: "get", chinese: "得到", pronunciation: "/ɡet/", example: "Get a present. 得到礼物。", tip: "获得某物" },
    { word: "put", chinese: "放", pronunciation: "/pʊt/", example: "Put book on table. 把书放在桌上。", tip: "放置某物" },
    { word: "make", chinese: "制作", pronunciation: "/meɪk/", example: "Make a cake. 做蛋糕。", tip: "创造某物" },
    { word: "use", chinese: "使用", pronunciation: "/juːz/", example: "Use a pencil. 使用铅笔。", tip: "利用某物" },
    { word: "find", chinese: "找到", pronunciation: "/faɪnd/", example: "Find my toy. 找到我的玩具。", tip: "发现某物" },
    { word: "lose", chinese: "丢失", pronunciation: "/luːz/", example: "Don't lose your key. 不要丢失钥匙。", tip: "找不到某物" },
    { word: "buy", chinese: "买", pronunciation: "/baɪ/", example: "Buy some apples. 买一些苹果。", tip: "用钱获得" },
    { word: "sell", chinese: "卖", pronunciation: "/sel/", example: "Sell old books. 卖旧书。", tip: "换钱给出" },
    { word: "clean", chinese: "清洁", pronunciation: "/kliːn/", example: "Clean your room. 清洁你的房间。", tip: "去除脏东西" },
    { word: "wash", chinese: "洗", pronunciation: "/wɑːʃ/", example: "Wash your hands. 洗手。", tip: "用水清洁" },
    { word: "cook", chinese: "烹饪", pronunciation: "/kʊk/", example: "Cook dinner tonight. 今晚做晚餐。", tip: "制作食物" },
    { word: "cut", chinese: "切", pronunciation: "/kʌt/", example: "Cut the apple. 切苹果。", tip: "用刀分开" },
    { word: "break", chinese: "打破", pronunciation: "/breɪk/", example: "Don't break the cup. 不要打破杯子。", tip: "使变成碎片" },
    { word: "fix", chinese: "修理", pronunciation: "/fɪks/", example: "Fix the broken toy. 修理坏玩具。", tip: "使恢复正常" },
    { word: "build", chinese: "建造", pronunciation: "/bɪld/", example: "Build a house. 建造房子。", tip: "创建结构" },
    { word: "carry", chinese: "携带", pronunciation: "/ˈkæri/", example: "Carry the bag. 携带包。", tip: "拿着移动" },
    { word: "push", chinese: "推", pronunciation: "/pʊʃ/", example: "Push the door. 推门。", tip: "用力向前" },
    { word: "pull", chinese: "拉", pronunciation: "/pʊl/", example: "Pull the rope. 拉绳子。", tip: "用力向后" },
    { word: "throw", chinese: "扔", pronunciation: "/θroʊ/", example: "Throw the ball. 扔球。", tip: "用力抛出" },
    { word: "catch", chinese: "接住", pronunciation: "/kætʃ/", example: "Catch the ball. 接住球。", tip: "用手抓住" },
    { word: "kick", chinese: "踢", pronunciation: "/kɪk/", example: "Kick the football. 踢足球。", tip: "用脚击打" },
    { word: "hit", chinese: "打击", pronunciation: "/hɪt/", example: "Hit the ball. 击球。", tip: "用力撞击" },
    { word: "count", chinese: "数数", pronunciation: "/kaʊnt/", example: "Count to ten. 数到十。", tip: "一个个地计算" },
    { word: "think", chinese: "思考", pronunciation: "/θɪŋk/", example: "Think before you act. 行动前要思考。", tip: "用脑子想" },

    // 描述词 (30个)
    { word: "nice", chinese: "好的", pronunciation: "/naɪs/", example: "You are very nice. 你很好。", tip: "令人喜欢的" },
    { word: "funny", chinese: "有趣的", pronunciation: "/ˈfʌni/", example: "The joke is funny. 这个笑话很有趣。", tip: "让人笑的" },
    { word: "smart", chinese: "聪明的", pronunciation: "/smɑːrt/", example: "You are very smart. 你很聪明。", tip: "头脑好的" },
    { word: "kind", chinese: "善良的", pronunciation: "/kaɪnd/", example: "Be kind to others. 对别人要善良。", tip: "心地好的" },
    { word: "brave", chinese: "勇敢的", pronunciation: "/breɪv/", example: "The boy is brave. 男孩很勇敢。", tip: "不害怕的" },
    { word: "quiet", chinese: "安静的", pronunciation: "/ˈkwaɪət/", example: "Please be quiet. 请安静。", tip: "没有声音的" },
    { word: "loud", chinese: "吵闹的", pronunciation: "/laʊd/", example: "The music is loud. 音乐很吵。", tip: "声音很大的" },
    { word: "bright", chinese: "明亮的", pronunciation: "/braɪt/", example: "The light is bright. 灯很亮。", tip: "光线强的" },
    { word: "dark", chinese: "黑暗的", pronunciation: "/dɑːrk/", example: "The room is dark. 房间很黑。", tip: "没有光的" },
    { word: "soft", chinese: "柔软的", pronunciation: "/sɔːft/", example: "The pillow is soft. 枕头很软。", tip: "不硬的" },
    { word: "hard", chinese: "坚硬的", pronunciation: "/hɑːrd/", example: "The rock is hard. 岩石很硬。", tip: "不软的" },
    { word: "smooth", chinese: "光滑的", pronunciation: "/smuːð/", example: "The table is smooth. 桌子很光滑。", tip: "表面平的" },
    { word: "rough", chinese: "粗糙的", pronunciation: "/rʌf/", example: "The wall is rough. 墙很粗糙。", tip: "表面不平的" },
    { word: "heavy", chinese: "重的", pronunciation: "/ˈhevi/", example: "The box is heavy. 箱子很重。", tip: "重量大的" },
    { word: "light", chinese: "轻的", pronunciation: "/laɪt/", example: "The feather is light. 羽毛很轻。", tip: "重量小的" },
    { word: "thick", chinese: "厚的", pronunciation: "/θɪk/", example: "The book is thick. 书很厚。", tip: "厚度大的" },
    { word: "thin", chinese: "薄的", pronunciation: "/θɪn/", example: "The paper is thin. 纸很薄。", tip: "厚度小的" },
    { word: "wide", chinese: "宽的", pronunciation: "/waɪd/", example: "The road is wide. 路很宽。", tip: "宽度大的" },
    { word: "narrow", chinese: "窄的", pronunciation: "/ˈnæroʊ/", example: "The path is narrow. 小径很窄。", tip: "宽度小的" },
    { word: "full", chinese: "满的", pronunciation: "/fʊl/", example: "The cup is full. 杯子满了。", tip: "装得很多的" },
    { word: "empty", chinese: "空的", pronunciation: "/ˈempti/", example: "The box is empty. 盒子是空的。", tip: "什么都没有的" },
    { word: "wet", chinese: "湿的", pronunciation: "/wet/", example: "The clothes are wet. 衣服湿了。", tip: "有水的" },
    { word: "dry", chinese: "干的", pronunciation: "/draɪ/", example: "The towel is dry. 毛巾是干的。", tip: "没有水的" },
    { word: "fresh", chinese: "新鲜的", pronunciation: "/freʃ/", example: "The fruit is fresh. 水果很新鲜。", tip: "刚刚的" },
    { word: "old", chinese: "老的", pronunciation: "/oʊld/", example: "The man is old. 男人很老。", tip: "年龄大的" },
    { word: "young", chinese: "年轻的", pronunciation: "/jʌŋ/", example: "The girl is young. 女孩很年轻。", tip: "年龄小的" },
    { word: "rich", chinese: "富有的", pronunciation: "/rɪtʃ/", example: "The family is rich. 这家人很富有。", tip: "钱很多的" },
    { word: "poor", chinese: "贫穷的", pronunciation: "/pʊr/", example: "Help the poor people. 帮助穷人。", tip: "钱很少的" },
    { word: "busy", chinese: "忙碌的", pronunciation: "/ˈbɪzi/", example: "Mom is very busy. 妈妈很忙。", tip: "事情很多的" },
    { word: "free", chinese: "空闲的", pronunciation: "/friː/", example: "I am free today. 我今天有空。", tip: "没有事情的" },

    // 常用介词和连词 (10个)
    { word: "and", chinese: "和", pronunciation: "/ænd/", example: "You and me. 你和我。", tip: "连接两个事物" },
    { word: "or", chinese: "或者", pronunciation: "/ɔːr/", example: "Apple or orange? 苹果还是橙子？", tip: "选择其中一个" },
    { word: "but", chinese: "但是", pronunciation: "/bʌt/", example: "Small but strong. 小但是强壮。", tip: "表示转折" },
    { word: "in", chinese: "在...里面", pronunciation: "/ɪn/", example: "Books are in bag. 书在包里。", tip: "内部位置" },
    { word: "on", chinese: "在...上面", pronunciation: "/ɑːn/", example: "Cat sits on table. 猫坐在桌上。", tip: "表面位置" },
    { word: "under", chinese: "在...下面", pronunciation: "/ˈʌndər/", example: "Dog sleeps under tree. 狗在树下睡觉。", tip: "下方位置" },
    { word: "over", chinese: "在...上方", pronunciation: "/ˈoʊvər/", example: "Bird flies over house. 鸟在房子上方飞。", tip: "上方位置" },
    { word: "near", chinese: "在...附近", pronunciation: "/nɪr/", example: "School is near home. 学校在家附近。", tip: "距离很近" },
    { word: "far", chinese: "远的", pronunciation: "/fɑːr/", example: "The mountain is far. 山很远。", tip: "距离很远" },
    { word: "between", chinese: "在...之间", pronunciation: "/bɪˈtwiːn/", example: "Sit between mom and dad. 坐在爸爸妈妈之间。", tip: "两者中间" }
  ],

  3: [
    // 3年级 - 学校生活和基础学科 (200个)
    
    // 学科相关 (30个)
    { word: "English", chinese: "英语", pronunciation: "/ˈɪŋɡlɪʃ/", example: "English is fun to learn. 学英语很有趣。", tip: "世界通用语言" },
    { word: "Chinese", chinese: "中文", pronunciation: "/ˌtʃaɪˈniːz/", example: "I speak Chinese well. 我中文说得好。", tip: "我们的母语" },
    { word: "history", chinese: "历史", pronunciation: "/ˈhɪstəri/", example: "History tells old stories. 历史讲述古老的故事。", tip: "过去发生的事" },
    { word: "geography", chinese: "地理", pronunciation: "/dʒiˈɑːɡrəfi/", example: "Geography studies places. 地理研究地方。", tip: "研究地球的科目" },
    { word: "biology", chinese: "生物", pronunciation: "/baɪˈɑːlədʒi/", example: "Biology studies living things. 生物学研究生物。", tip: "研究生命的科目" },
    { word: "chemistry", chinese: "化学", pronunciation: "/ˈkemɪstri/", example: "Chemistry mixes elements. 化学混合元素。", tip: "研究物质变化" },
    { word: "physics", chinese: "物理", pronunciation: "/ˈfɪzɪks/", example: "Physics explains how things move. 物理解释事物如何运动。", tip: "研究运动和力" },
    { word: "computer", chinese: "计算机", pronunciation: "/kəmˈpjuːtər/", example: "Use computer to learn. 用计算机学习。", tip: "电子学习工具" },
    { word: "technology", chinese: "技术", pronunciation: "/tekˈnɑːlədʒi/", example: "Technology helps us work. 技术帮助我们工作。", tip: "现代的工具方法" },
    { word: "experiment", chinese: "实验", pronunciation: "/ɪkˈsperɪmənt/", example: "Do science experiments. 做科学实验。", tip: "验证知识的活动" },
    { word: "research", chinese: "研究", pronunciation: "/rɪˈsɜːrtʃ/", example: "Research new information. 研究新信息。", tip: "深入了解问题" },
    { word: "project", chinese: "项目", pronunciation: "/ˈprɑːdʒekt/", example: "Work on school project. 做学校项目。", tip: "完成的任务" },
    { word: "report", chinese: "报告", pronunciation: "/rɪˈpɔːrt/", example: "Write a book report. 写读书报告。", tip: "汇报学习成果" },
    { word: "presentation", chinese: "演示", pronunciation: "/ˌpriːzenˈteɪʃn/", example: "Give a presentation. 做演示。", tip: "向别人展示" },
    { word: "quiz", chinese: "小测验", pronunciation: "/kwɪz/", example: "Take a math quiz. 参加数学小测验。", tip: "简短的考试" },
    { word: "exam", chinese: "考试", pronunciation: "/ɪɡˈzæm/", example: "Study for the exam. 为考试而学习。", tip: "正式的测试" },
    { word: "answer", chinese: "答案", pronunciation: "/ˈænsər/", example: "Find the right answer. 找到正确答案。", tip: "问题的解决" },
    { word: "question", chinese: "问题", pronunciation: "/ˈkwestʃən/", example: "Ask a good question. 问一个好问题。", tip: "需要回答的询问" },
    { word: "solution", chinese: "解决方案", pronunciation: "/səˈluːʃn/", example: "Find solution to problem. 找到问题的解决方案。", tip: "问题的答案" },
    { word: "method", chinese: "方法", pronunciation: "/ˈmeθəd/", example: "Use good study method. 使用好的学习方法。", tip: "做事的方式" },
    { word: "skill", chinese: "技能", pronunciation: "/skɪl/", example: "Learn new skills. 学习新技能。", tip: "做事的能力" },
    { word: "knowledge", chinese: "知识", pronunciation: "/ˈnɑːlɪdʒ/", example: "Knowledge is power. 知识就是力量。", tip: "学到的内容" },
    { word: "practice", chinese: "练习", pronunciation: "/ˈpræktɪs/", example: "Practice makes perfect. 熟能生巧。", tip: "重复做某事" },
    { word: "memory", chinese: "记忆", pronunciation: "/ˈmeməri/", example: "Good memory helps learning. 好记忆帮助学习。", tip: "记住信息的能力" },
    { word: "attention", chinese: "注意力", pronunciation: "/əˈtenʃn/", example: "Pay attention in class. 上课要注意听讲。", tip: "专心的状态" },
    { word: "focus", chinese: "专注", pronunciation: "/ˈfoʊkəs/", example: "Focus on your work. 专注于你的工作。", tip: "集中精力" },
    { word: "understand", chinese: "理解", pronunciation: "/ˌʌndərˈstænd/", example: "I understand the lesson. 我理解这课。", tip: "知道意思" },
    { word: "explain", chinese: "解释", pronunciation: "/ɪkˈspleɪn/", example: "Teacher explains the rule. 老师解释规则。", tip: "说明原因" },
    { word: "learn", chinese: "学习", pronunciation: "/lɜːrn/", example: "Learn something new everyday. 每天学新东西。", tip: "获得知识" },
    { word: "teach", chinese: "教", pronunciation: "/tiːtʃ/", example: "Teacher teaches us math. 老师教我们数学。", tip: "传授知识" },

    // 活动类 (25个)
    { word: "activity", chinese: "活动", pronunciation: "/ækˈtɪvəti/", example: "Join school activities. 参加学校活动。", tip: "做的事情" },
    { word: "game", chinese: "游戏", pronunciation: "/ɡeɪm/", example: "Play fun games. 玩有趣的游戏。", tip: "娱乐的方式" },
    { word: "sport", chinese: "运动", pronunciation: "/spɔːrt/", example: "Sports keep us healthy. 运动让我们健康。", tip: "锻炼身体的活动" },
    { word: "football", chinese: "足球", pronunciation: "/ˈfʊtbɔːl/", example: "Play football after school. 放学后踢足球。", tip: "用脚踢的球类" },
    { word: "basketball", chinese: "篮球", pronunciation: "/ˈbæskɪtbɔːl/", example: "Basketball needs tall players. 篮球需要高个子球员。", tip: "投篮的球类" },
    { word: "volleyball", chinese: "排球", pronunciation: "/ˈvɑːlibɔːl/", example: "Volleyball is team sport. 排球是团队运动。", tip: "用手打的球类" },
    { word: "tennis", chinese: "网球", pronunciation: "/ˈtenɪs/", example: "Tennis uses racket. 网球使用球拍。", tip: "用拍子打的球类" },
    { word: "swimming", chinese: "游泳", pronunciation: "/ˈswɪmɪŋ/", example: "Swimming is good exercise. 游泳是很好的运动。", tip: "在水中的运动" },
    { word: "running", chinese: "跑步", pronunciation: "/ˈrʌnɪŋ/", example: "Running makes legs strong. 跑步让腿部强壮。", tip: "快速移动的运动" },
    { word: "jumping", chinese: "跳跃", pronunciation: "/ˈdʒʌmpɪŋ/", example: "Jumping rope is fun. 跳绳很有趣。", tip: "向上弹起的动作" },
    { word: "climbing", chinese: "攀爬", pronunciation: "/ˈklaɪmɪŋ/", example: "Climbing trees is dangerous. 爬树很危险。", tip: "向上移动的动作" },
    { word: "cycling", chinese: "骑自行车", pronunciation: "/ˈsaɪklɪŋ/", example: "Cycling is eco-friendly. 骑自行车环保。", tip: "骑车的活动" },
    { word: "hiking", chinese: "远足", pronunciation: "/ˈhaɪkɪŋ/", example: "Go hiking in mountains. 去山里远足。", tip: "长距离步行" },
    { word: "camping", chinese: "野营", pronunciation: "/ˈkæmpɪŋ/", example: "Camping under stars. 在星空下野营。", tip: "户外过夜活动" },
    { word: "fishing", chinese: "钓鱼", pronunciation: "/ˈfɪʃɪŋ/", example: "Fishing needs patience. 钓鱼需要耐心。", tip: "捕鱼的活动" },
    { word: "cooking", chinese: "烹饪", pronunciation: "/ˈkʊkɪŋ/", example: "Cooking is useful skill. 烹饪是有用的技能。", tip: "制作食物的活动" },
    { word: "painting", chinese: "绘画", pronunciation: "/ˈpeɪntɪŋ/", example: "Painting needs creativity. 绘画需要创造力。", tip: "用颜料创作" },
    { word: "drawing", chinese: "画画", pronunciation: "/ˈdrɔːɪŋ/", example: "Drawing improves observation. 画画提高观察力。", tip: "用笔创作图画" },
    { word: "reading", chinese: "阅读", pronunciation: "/ˈriːdɪŋ/", example: "Reading expands knowledge. 阅读扩展知识。", tip: "看书获取信息" },
    { word: "writing", chinese: "写作", pronunciation: "/ˈraɪtɪŋ/", example: "Writing improves thinking. 写作提高思维。", tip: "用文字表达" },
    { word: "singing", chinese: "唱歌", pronunciation: "/ˈsɪŋɪŋ/", example: "Singing brings joy. 唱歌带来快乐。", tip: "用声音创作音乐" },
    { word: "dancing", chinese: "跳舞", pronunciation: "/ˈdænsɪŋ/", example: "Dancing expresses feelings. 跳舞表达感情。", tip: "用身体表达节奏" },
    { word: "acting", chinese: "表演", pronunciation: "/ˈæktɪŋ/", example: "Acting needs practice. 表演需要练习。", tip: "扮演角色" },
    { word: "competition", chinese: "比赛", pronunciation: "/ˌkɑːmpəˈtɪʃn/", example: "Win the competition. 赢得比赛。", tip: "争夺第一的活动" },
    { word: "team", chinese: "团队", pronunciation: "/tiːm/", example: "Work as a team. 作为团队工作。", tip: "一起合作的群体" },

    // 情感词汇 (20个)
    { word: "feel", chinese: "感觉", pronunciation: "/fiːl/", example: "I feel happy today. 我今天感觉快乐。", tip: "内心的状态" },
    { word: "emotion", chinese: "情感", pronunciation: "/ɪˈmoʊʃn/", example: "Show your emotions. 表达你的情感。", tip: "内心的感受" },
    { word: "excited", chinese: "兴奋的", pronunciation: "/ɪkˈsaɪtɪd/", example: "I'm excited about trip. 我对旅行很兴奋。", tip: "很激动的感觉" },
    { word: "surprised", chinese: "惊讶的", pronunciation: "/sərˈpraɪzd/", example: "I'm surprised by gift. 我对礼物很惊讶。", tip: "意外的感觉" },
    { word: "worried", chinese: "担心的", pronunciation: "/ˈwɜːrid/", example: "Don't be worried. 不要担心。", tip: "害怕不好事情" },
    { word: "angry", chinese: "生气的", pronunciation: "/ˈæŋɡri/", example: "Don't get angry. 不要生气。", tip: "不高兴的感觉" },
    { word: "scared", chinese: "害怕的", pronunciation: "/skerd/", example: "Don't be scared. 不要害怕。", tip: "恐惧的感觉" },
    { word: "nervous", chinese: "紧张的", pronunciation: "/ˈnɜːrvəs/", example: "Feel nervous before test. 考试前感到紧张。", tip: "不安的感觉" },
    { word: "calm", chinese: "平静的", pronunciation: "/kɑːm/", example: "Stay calm and think. 保持冷静思考。", tip: "不激动的状态" },
    { word: "relaxed", chinese: "放松的", pronunciation: "/rɪˈlækst/", example: "Feel relaxed on weekend. 周末感到放松。", tip: "不紧张的状态" },
    { word: "tired", chinese: "疲倦的", pronunciation: "/ˈtaɪərd/", example: "I'm tired after running. 跑步后我很累。", tip: "需要休息的感觉" },
    { word: "sleepy", chinese: "困倦的", pronunciation: "/ˈsliːpi/", example: "Feel sleepy at night. 晚上感到困倦。", tip: "想睡觉的感觉" },
    { word: "hungry", chinese: "饥饿的", pronunciation: "/ˈhʌŋɡri/", example: "I'm hungry for lunch. 我饿了想吃午餐。", tip: "想吃东西的感觉" },
    { word: "thirsty", chinese: "口渴的", pronunciation: "/ˈθɜːrsti/", example: "Drink water when thirsty. 渴了就喝水。", tip: "想喝水的感觉" },
    { word: "comfortable", chinese: "舒适的", pronunciation: "/ˈkʌmftəbl/", example: "Sit in comfortable chair. 坐在舒适的椅子上。", tip: "感觉很好的状态" },
    { word: "uncomfortable", chinese: "不舒服的", pronunciation: "/ʌnˈkʌmftəbl/", example: "Hard bed is uncomfortable. 硬床不舒服。", tip: "感觉不好的状态" },
    { word: "proud", chinese: "自豪的", pronunciation: "/praʊd/", example: "I'm proud of my work. 我为我的工作感到自豪。", tip: "满意自己的成就" },
    { word: "ashamed", chinese: "羞愧的", pronunciation: "/əˈʃeɪmd/", example: "Feel ashamed of mistake. 为错误感到羞愧。", tip: "对自己不满意" },
    { word: "lonely", chinese: "孤独的", pronunciation: "/ˈloʊnli/", example: "Don't feel lonely. 不要感到孤独。", tip: "缺少朋友的感觉" },
    { word: "grateful", chinese: "感激的", pronunciation: "/ˈɡreɪtfl/", example: "Be grateful for help. 对帮助要感激。", tip: "感谢别人的心情" },

    // 自然科学 (25个)
    { word: "nature", chinese: "自然", pronunciation: "/ˈneɪtʃər/", example: "Nature is beautiful. 自然很美丽。", tip: "未被人类改变的环境" },
    { word: "environment", chinese: "环境", pronunciation: "/ɪnˈvaɪrənmənt/", example: "Protect our environment. 保护我们的环境。", tip: "周围的条件" },
    { word: "planet", chinese: "行星", pronunciation: "/ˈplænɪt/", example: "Earth is our planet. 地球是我们的行星。", tip: "围绕太阳的天体" },
    { word: "earth", chinese: "地球", pronunciation: "/ɜːrθ/", example: "Earth is our home. 地球是我们的家。", tip: "我们居住的星球" },
    { word: "space", chinese: "太空", pronunciation: "/speɪs/", example: "Stars are in space. 星星在太空中。", tip: "地球之外的地方" },
    { word: "universe", chinese: "宇宙", pronunciation: "/ˈjuːnɪvɜːrs/", example: "Universe is very big. 宇宙很大。", tip: "包含一切的空间" },
    { word: "galaxy", chinese: "星系", pronunciation: "/ˈɡæləksi/", example: "Our galaxy has many stars. 我们的星系有很多星星。", tip: "很多星星的集合" },
    { word: "solar", chinese: "太阳的", pronunciation: "/ˈsoʊlər/", example: "Solar system has planets. 太阳系有行星。", tip: "与太阳相关的" },
    { word: "atom", chinese: "原子", pronunciation: "/ˈætəm/", example: "Atoms are very small. 原子很小。", tip: "物质的最小单位" },
    { word: "molecule", chinese: "分子", pronunciation: "/ˈmɑːlɪkjuːl/", example: "Water has molecules. 水有分子。", tip: "原子组成的群体" },
    { word: "energy", chinese: "能量", pronunciation: "/ˈenərdʒi/", example: "Food gives us energy. 食物给我们能量。", tip: "做功的能力" },
    { word: "force", chinese: "力", pronunciation: "/fɔːrs/", example: "Push with more force. 用更大的力推。", tip: "使物体运动的原因" },
    { word: "gravity", chinese: "重力", pronunciation: "/ˈɡrævəti/", example: "Gravity pulls things down. 重力把东西拉下来。", tip: "地球的吸引力" },
    { word: "motion", chinese: "运动", pronunciation: "/ˈmoʊʃn/", example: "Everything is in motion. 一切都在运动。", tip: "位置的改变" },
    { word: "speed", chinese: "速度", pronunciation: "/spiːd/", example: "Light travels at high speed. 光以高速传播。", tip: "运动的快慢" },
    { word: "sound", chinese: "声音", pronunciation: "/saʊnd/", example: "Sound travels through air. 声音通过空气传播。", tip: "听到的波动" },
    { word: "vibration", chinese: "振动", pronunciation: "/vaɪˈbreɪʃn/", example: "Vibration makes sound. 振动产生声音。", tip: "快速来回运动" },
    { word: "heat", chinese: "热", pronunciation: "/hiːt/", example: "Heat comes from sun. 热来自太阳。", tip: "温度高的能量" },
    { word: "temperature", chinese: "温度", pronunciation: "/ˈtemprətʃər/", example: "Check water temperature. 检查水温。", tip: "热冷的程度" },
    { word: "electricity", chinese: "电", pronunciation: "/ɪˌlekˈtrɪsəti/", example: "Electricity powers lights. 电给灯供电。", tip: "电子流动的能量" },
    { word: "magnet", chinese: "磁铁", pronunciation: "/ˈmæɡnət/", example: "Magnet attracts iron. 磁铁吸引铁。", tip: "有磁性的物体" },
    { word: "material", chinese: "材料", pronunciation: "/məˈtɪriəl/", example: "Wood is building material. 木头是建筑材料。", tip: "制作东西的物质" },
    { word: "metal", chinese: "金属", pronunciation: "/ˈmetl/", example: "Iron is a metal. 铁是一种金属。", tip: "坚硬有光泽的物质" },
    { word: "plastic", chinese: "塑料", pronunciation: "/ˈplæstɪk/", example: "Toys are made of plastic. 玩具是塑料做的。", tip: "人工合成的材料" },
    { word: "glass", chinese: "玻璃", pronunciation: "/ɡlæs/", example: "Glass is transparent. 玻璃是透明的。", tip: "透明的硬质材料" },

    // 植物动物 (25个)
    { word: "plant", chinese: "植物", pronunciation: "/plænt/", example: "Plants need water. 植物需要水。", tip: "会生长的绿色生物" },
    { word: "tree", chinese: "树", pronunciation: "/triː/", example: "Trees give us shade. 树给我们阴凉。", tip: "高大的植物" },
    { word: "flower", chinese: "花", pronunciation: "/ˈflaʊər/", example: "Flowers smell nice. 花闻起来很香。", tip: "植物美丽的部分" },
    { word: "leaf", chinese: "叶子", pronunciation: "/liːf/", example: "Leaves turn yellow. 叶子变黄。", tip: "植物的绿色部分" },
    { word: "root", chinese: "根", pronunciation: "/ruːt/", example: "Roots grow underground. 根在地下生长。", tip: "植物在土里的部分" },
    { word: "stem", chinese: "茎", pronunciation: "/stem/", example: "Stem supports the flower. 茎支撑花朵。", tip: "植物的主干" },
    { word: "seed", chinese: "种子", pronunciation: "/siːd/", example: "Plant seeds in soil. 把种子种在土里。", tip: "植物的繁殖体" },
    { word: "fruit", chinese: "水果", pronunciation: "/fruːt/", example: "Fruits are healthy food. 水果是健康食物。", tip: "植物的甜美部分" },
    { word: "vegetable", chinese: "蔬菜", pronunciation: "/ˈvedʒtəbl/", example: "Eat more vegetables. 多吃蔬菜。", tip: "植物的营养部分" },
    { word: "grass", chinese: "草", pronunciation: "/ɡræs/", example: "Grass is green. 草是绿色的。", tip: "地面的小植物" },
    { word: "bush", chinese: "灌木", pronunciation: "/bʊʃ/", example: "Birds nest in bush. 鸟在灌木里筑巢。", tip: "矮小的植物群" },
    { word: "forest", chinese: "森林", pronunciation: "/ˈfɔːrɪst/", example: "Forest has many animals. 森林有很多动物。", tip: "很多树的地方" },
    { word: "jungle", chinese: "丛林", pronunciation: "/ˈdʒʌŋɡl/", example: "Jungle is thick forest. 丛林是茂密的森林。", tip: "热带密林" },
    { word: "desert", chinese: "沙漠", pronunciation: "/ˈdezərt/", example: "Desert is very dry. 沙漠很干燥。", tip: "很少下雨的地方" },
    { word: "ocean", chinese: "海洋", pronunciation: "/ˈoʊʃn/", example: "Ocean is very deep. 海洋很深。", tip: "很大的咸水体" },
    { word: "sea", chinese: "海", pronunciation: "/siː/", example: "Fish live in the sea. 鱼生活在海里。", tip: "咸水的地方" },
    { word: "pond", chinese: "池塘", pronunciation: "/pɑːnd/", example: "Frogs live in pond. 青蛙住在池塘里。", tip: "小的水体" },
    { word: "stream", chinese: "小溪", pronunciation: "/striːm/", example: "Stream flows to river. 小溪流向河流。", tip: "流动的小水道" },
    { word: "valley", chinese: "山谷", pronunciation: "/ˈvæli/", example: "Valley is between mountains. 山谷在山之间。", tip: "山之间的低地" },
    { word: "hill", chinese: "小山", pronunciation: "/hɪl/", example: "Climb up the hill. 爬上小山。", tip: "比较矮的山" },
    { word: "cave", chinese: "洞穴", pronunciation: "/keɪv/", example: "Bats live in caves. 蝙蝠住在洞穴里。", tip: "山里的空洞" },
    { word: "rock", chinese: "岩石", pronunciation: "/rɑːk/", example: "Rock is very hard. 岩石很硬。", tip: "坚硬的石头" },
    { word: "soil", chinese: "土壤", pronunciation: "/sɔɪl/", example: "Plants grow in soil. 植物在土壤中生长。", tip: "植物生长的泥土" },
    { word: "sand", chinese: "沙子", pronunciation: "/sænd/", example: "Sand is at the beach. 海滩上有沙子。", tip: "很小的石粒" },
    { word: "island", chinese: "岛屿", pronunciation: "/ˈaɪlənd/", example: "Island is surrounded by water. 岛屿被水包围。", tip: "被水围绕的陆地" },

    // 日常用语 (25个)
    { word: "hello", chinese: "你好", pronunciation: "/həˈloʊ/", example: "Hello, how are you? 你好，你好吗？", tip: "见面的问候语" },
    { word: "goodbye", chinese: "再见", pronunciation: "/ɡʊdˈbaɪ/", example: "Goodbye, see you tomorrow. 再见，明天见。", tip: "告别的话" },
    { word: "please", chinese: "请", pronunciation: "/pliːz/", example: "Please help me. 请帮助我。", tip: "礼貌请求的词" },
    { word: "thanks", chinese: "谢谢", pronunciation: "/θæŋks/", example: "Thanks for your help. 谢谢你的帮助。", tip: "表示感谢" },
    { word: "sorry", chinese: "对不起", pronunciation: "/ˈsɔːri/", example: "Sorry for being late. 对不起迟到了。", tip: "道歉的话" },
    { word: "excuse", chinese: "原谅", pronunciation: "/ɪkˈskjuːs/", example: "Excuse me, where is library? 打扰一下，图书馆在哪？", tip: "礼貌地引起注意" },
    { word: "welcome", chinese: "欢迎", pronunciation: "/ˈwelkəm/", example: "Welcome to our school. 欢迎来到我们学校。", tip: "友好接待" },
    { word: "congratulations", chinese: "祝贺", pronunciation: "/kənˌɡrætʃəˈleɪʃnz/", example: "Congratulations on your success. 祝贺你的成功。", tip: "庆祝成就" },
    { word: "birthday", chinese: "生日", pronunciation: "/ˈbɜːrθdeɪ/", example: "Happy birthday! 生日快乐！", tip: "出生的纪念日" },
    { word: "holiday", chinese: "假期", pronunciation: "/ˈhɑːlədeɪ/", example: "Enjoy your holiday. 享受你的假期。", tip: "休息的日子" },
    { word: "vacation", chinese: "度假", pronunciation: "/veɪˈkeɪʃn/", example: "Summer vacation is fun. 暑假很有趣。", tip: "长时间的休息" },
    { word: "party", chinese: "聚会", pronunciation: "/ˈpɑːrti/", example: "Come to my birthday party. 来参加我的生日聚会。", tip: "庆祝的活动" },
    { word: "gift", chinese: "礼物", pronunciation: "/ɡɪft/", example: "Give a gift to friend. 给朋友一个礼物。", tip: "表示心意的物品" },
    { word: "present", chinese: "礼品", pronunciation: "/ˈpreznt/", example: "Open your present. 打开你的礼品。", tip: "赠送的物品" },
    { word: "surprise", chinese: "惊喜", pronunciation: "/sərˈpraɪz/", example: "What a nice surprise! 多么好的惊喜！", tip: "意想不到的好事" },
    { word: "lucky", chinese: "幸运的", pronunciation: "/ˈlʌki/", example: "You are very lucky. 你很幸运。", tip: "好运气的" },
    { word: "unlucky", chinese: "不幸的", pronunciation: "/ʌnˈlʌki/", example: "Don't feel unlucky. 不要觉得不幸。", tip: "运气不好的" },
    { word: "careful", chinese: "小心的", pronunciation: "/ˈkerfl/", example: "Be careful crossing road. 过马路要小心。", tip: "注意安全的" },
    { word: "dangerous", chinese: "危险的", pronunciation: "/ˈdeɪndʒərəs/", example: "Fire is dangerous. 火是危险的。", tip: "可能伤害的" },
    { word: "safe", chinese: "安全的", pronunciation: "/seɪf/", example: "This place is safe. 这个地方很安全。", tip: "没有危险的" },
    { word: "important", chinese: "重要的", pronunciation: "/ɪmˈpɔːrtnt/", example: "Health is important. 健康很重要。", tip: "很有价值的" },
    { word: "special", chinese: "特别的", pronunciation: "/ˈspeʃl/", example: "Today is special day. 今天是特别的日子。", tip: "与众不同的" },
    { word: "normal", chinese: "正常的", pronunciation: "/ˈnɔːrml/", example: "This is normal behavior. 这是正常行为。", tip: "普通常见的" },
    { word: "different", chinese: "不同的", pronunciation: "/ˈdɪfrənt/", example: "We are all different. 我们都不同。", tip: "不一样的" },
    { word: "same", chinese: "相同的", pronunciation: "/seɪm/", example: "We have same hobby. 我们有相同的爱好。", tip: "一样的" },

    // 基础数学 (25个)
    { word: "number", chinese: "数字", pronunciation: "/ˈnʌmbər/", example: "Write the number. 写这个数字。", tip: "表示数量的符号" },
    { word: "count", chinese: "计数", pronunciation: "/kaʊnt/", example: "Count from one to ten. 从一数到十。", tip: "一个个地计算" },
    { word: "add", chinese: "加", pronunciation: "/æd/", example: "Add two and three. 二加三。", tip: "求和的运算" },
    { word: "subtract", chinese: "减", pronunciation: "/səbˈtrækt/", example: "Subtract one from five. 五减一。", tip: "求差的运算" },
    { word: "multiply", chinese: "乘", pronunciation: "/ˈmʌltɪplaɪ/", example: "Multiply two by three. 二乘以三。", tip: "求积的运算" },
    { word: "divide", chinese: "除", pronunciation: "/dɪˈvaɪd/", example: "Divide six by two. 六除以二。", tip: "求商的运算" },
    { word: "equal", chinese: "等于", pronunciation: "/ˈiːkwəl/", example: "Two plus two equals four. 二加二等于四。", tip: "数量相同" },
    { word: "plus", chinese: "加号", pronunciation: "/plʌs/", example: "Use plus sign. 使用加号。", tip: "加法的符号" },
    { word: "minus", chinese: "减号", pronunciation: "/ˈmaɪnəs/", example: "Use minus sign. 使用减号。", tip: "减法的符号" },
    { word: "times", chinese: "乘号", pronunciation: "/taɪmz/", example: "Three times four. 三乘以四。", tip: "乘法的表示" },
    { word: "half", chinese: "一半", pronunciation: "/hæf/", example: "Cut apple in half. 把苹果切成一半。", tip: "二分之一" },
    { word: "quarter", chinese: "四分之一", pronunciation: "/ˈkwɔːrtər/", example: "Quarter of cake. 四分之一的蛋糕。", tip: "四等分之一" },
    { word: "double", chinese: "双倍", pronunciation: "/ˈdʌbl/", example: "Double the amount. 双倍的数量。", tip: "两倍的" },
    { word: "triple", chinese: "三倍", pronunciation: "/ˈtrɪpl/", example: "Triple the speed. 三倍的速度。", tip: "三倍的" },
    { word: "whole", chinese: "整个", pronunciation: "/hoʊl/", example: "Eat the whole apple. 吃整个苹果。", tip: "完整的全部" },
    { word: "part", chinese: "部分", pronunciation: "/pɑːrt/", example: "This is part of story. 这是故事的一部分。", tip: "不完整的一些" },
    { word: "total", chinese: "总数", pronunciation: "/ˈtoʊtl/", example: "What's the total? 总数是多少？", tip: "全部加起来的数" },
    { word: "average", chinese: "平均", pronunciation: "/ˈævərɪdʒ/", example: "Find the average. 找出平均值。", tip: "总数除以个数" },
    { word: "measure", chinese: "测量", pronunciation: "/ˈmeʒər/", example: "Measure the length. 测量长度。", tip: "确定大小数量" },
    { word: "length", chinese: "长度", pronunciation: "/leŋθ/", example: "What's the length? 长度是多少？", tip: "从头到尾的距离" },
    { word: "width", chinese: "宽度", pronunciation: "/wɪdθ/", example: "Measure the width. 测量宽度。", tip: "从左到右的距离" },
    { word: "height", chinese: "高度", pronunciation: "/haɪt/", example: "Check the height. 检查高度。", tip: "从下到上的距离" },
    { word: "size", chinese: "尺寸", pronunciation: "/saɪz/", example: "What size do you want? 你要什么尺寸？", tip: "大小的规格" },
    { word: "shape", chinese: "形状", pronunciation: "/ʃeɪp/", example: "Draw different shapes. 画不同的形状。", tip: "物体的外形" },
    { word: "circle", chinese: "圆形", pronunciation: "/ˈsɜːrkl/", example: "Draw a circle. 画一个圆。", tip: "圆圆的形状" }
  ]
};

export default wordDatabase;